/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElPopconfirm: (typeof import('element-plus/es'))['ElPopconfirm']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
  }
}
